### ISSUE TITLE
Unit Test failed for openmlweka.TestFlowSerialization

### ISSUE THREAD

**Issue by eaudet** [openml/openml-weka#13]
Hi,

Clone yesterday and cannot build without skipping test. It seems like the xml obtained by xstream does not have/or points to right schema.

stack trace:
---------------------------
org.openml.apiconnector.io.ApiException: Problem validating uploaded description file: XML does not correspond to XSD schema. 

	at org.openml.apiconnector.io.HttpConnector.wrapHttpResponse(HttpConnector.java:91)
	at org.openml.apiconnector.io.HttpConnector.doApiRequest(HttpConnector.java:45)
	at org.openml.apiconnector.io.OpenmlConnector.flowUpload(OpenmlConnector.java:710)
	at openmlweka.TestFlowSerialization.testSimpleFlow(TestFlowSerialization.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
----------------------

**Comment by janvanrijn** [comment]
Thanks for reporting this! 

This is not an Xstream problem. Weka and OpenML communicate through an XML schema, verified by XSD, which we made more strict this week. Apparently too strict. I'll have a look.

**Comment by janvanrijn** [comment]
Should work, please close
