### ISSUE TITLE
null error on run

### ISSUE THREAD

**Issue by Krulvis** [openml/openml-weka#15]
When running a task in Weka I'm getting the following error:

```
Writing experiment copy
Reading experiment copy
Made experiment copy
CrossValidationResultProducer: setting additional measures for split evaluator
[10-10-2018 17:54:10] [OK] [Cache] Obtained from cache: datadescription/datadescription_41198.xml
[10-10-2018 17:54:10] [OK] [Cache] Obtained from cache: dataset/dataset_41198.ARFF
java.lang.NullPointerException
	org.openml.weka.algorithm.InstancesHelper.getDatasetFromTask(InstancesHelper.java:97)
	org.openml.weka.experiment.TaskResultProducer.setTask(TaskResultProducer.java:117)
	org.openml.weka.experiment.TaskBasedExperiment.nextIteration(TaskBasedExperiment.java:147)
	weka.gui.experiment.RunPanel$ExperimentRunner.run(RunPanel.java:180)

	at org.openml.weka.algorithm.InstancesHelper.getDatasetFromTask(InstancesHelper.java:97)
	at org.openml.weka.experiment.TaskResultProducer.setTask(TaskResultProducer.java:117)
	at org.openml.weka.experiment.TaskBasedExperiment.nextIteration(TaskBasedExperiment.java:147)
	at weka.gui.experiment.RunPanel$ExperimentRunner.run(RunPanel.java:180)
Done...
```
Weka version 3.8.2

**Comment by janvanrijn** [comment]
Thanks for reporting this error. 

Can you please give some information on which classifier and hyperparameter settings you were using? Also, what is the version of the openml-weka package?

**Comment by Krulvis** [comment]
Ah excuse me, I edited the issue to be more informative.
I ran a RandomForest without changing any of the settings.
![image](https://user-images.githubusercontent.com/21366036/46755204-c8d72780-ccc4-11e8-8853-e35c7f330fe5.png)

**Comment by janvanrijn** [comment]
I am a little bit confused by the error. It implies that there is a task `41198`, but this one is not present op OpenML: https://www.openml.org/t/41196

**Comment by janvanrijn** [comment]
My bad, it has to be task 168349. I am encountering the same problem. Will investigate.

**Comment by Krulvis** [comment]
Any updates on the issue?

**Comment by janvanrijn** [comment]
Hi @Krulvis , this week I created a new release, it should resolve your problems. Can you please verify this?
